spring:
  data:
    redis:
      host: redis
      port: 6379

springdoc:
  api-docs:
    path: /admin/api-docs
  swagger-ui:
    path: /admin/swagger-ui

logging:
  level:
    me.ex1tus.mancala.game.rule: DEBUG

game:
  pits-in-row: 6
  stones-in-pit: 6

features:
  redis:
    enabled: true
  stomp:
    topic: /topic/games/
    enabled: true
  http-logging:
    enabled: true